[UI/#6/#9] CategoryFragment 뷰 / UI 구현
DO-SOPT-CDS-APP-2/CDS-APP-2-ANDROID pull request #13
Opened 2023-11-24 16:33 UTC by codingmy

- closed #6
- closed #9  

## *⛳️ Work Description*
- toolBar 구현 (검색창 라인)
- RecyclerView로 상단 가로스크롤, 좌측하단 상위카테고리 스크롤 구현
- NestedScrollView로 칩스, 광고배너, 우측하단 하위카테고리를 하나로 스크롤 구현

## *📸 Screenshot*

https://github.com/DO-SOPT-CDS-APP-2/CDS-APP-2-ANDROID/assets/97686638/72380384-dbd1-4275-afa8-1e8bed24e080

## *📢 To Reviewers*
- 영어 한글 폰트 다른걸 방금 발견해서...폰트 설정은 투비컨티뉴
- 상단 카테고리 이미지 추출했는데 저 29 저 이미지만 떠서 일단 더미로 넣어놨습니다 이 또한 투비컨티뉴
- 칩스 테두리...또한 투비컨티뉴
- 뭔가 저 상단바를 완성하고 나서 pr을 올렸어야 되는거 같지만 일단 pr 합쳐서 올립니당

2023-11-24 16:55 UTC, Marchbreeze requested changes
애정을 꾹꾹 담아 코드리뷰 잔뜩 남겨드려요 ㅎㅎ
fontFamily 변경이랑, xml에서 네이밍 수정 & 고정된 크기 변경 진행하시면 어프루브 드리겟습니당

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
> +    private val viewModel by viewModels<CategoryViewModel>()
오옷 뷰모델을 쓰다니

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
> +        binding.rvCategoryHorizontal.adapter = categoryHorizontalAdapter
이렇게 코드 블럭은  '가로 스크롤 카테고리' 에 대해서 생성하고, 아이템 넣고, 바인딩에 붙이는 작업이니 하나의 흐름이라고 볼 수 있겠죠?
함수화를 진행하고, onViewCreated()에는 생성한 함수명들만 채우는 연습을 한번 해봅시당 ~~~~

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
> +        return binding.root
굿굿! 근데 _binding을 활용했으면 onDestroyView()에서 꼭 null로 해제시켜주어야합니다 ~~
어댑터도 _adapter 형태로 상요할 수 있는데, 요거는 나중에 제 코드 보면서 참고해봐요 ~~

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalAdapter.kt
> +    private val inflater by lazy { LayoutInflater.from(context) }
코드 좋네요 ~

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalAdapter.kt
> +    override fun getItemCount()= CategoryHorizontalList.size
여기 ()= 간격 보니깐 코드 최적화 진행 안한듯요 ㅎㅎ 꼭 정리를 하고 PR로 올려두는 습관을 길러봅시닷

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalViewHolder.kt
> +            binding.ivCategoryHorizontal.setImageResource(categoryHorizontalData.categoryImage)
물~론 binding이 2개밖에 없어서 굳이 스코프 함수를 안써도 되지만, 저라면 습관화를 위해 이렇게 작성했을 것 같아요
```suggestion
            with(binding) {
                    tvCategoryHorizontal.text = categoryHorizontalData.categoryName
                    ivCategoryHorizontal.setImageResource(categoryHorizontalData.categoryImage)
            }
```

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +        android:layout_height="58dp"
높이를 지정하는 것은 좋지 않아요 ~~ wrap_content와 패딩값 마진값을 활용해봅시다

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +            android:layout_marginBottom="15dp"
상하나 좌우에 같은 마진을 준다면 layout_marginVertical 과 Horizontal 을 활용해봅시당

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +                android:layout_width="187dp"
이것도! 금지입니다 ~~ 크기를 지정해주면 안되고, constraint를 통해서 양쪽에 제약을 준 다음에 패딩과 마진으로 조절해야해요

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +                android:id="@+id/iv_category_searchIcon"
네이밍 주의! search_icon으로 수정해주세요

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +        android:layout_marginEnd="0dp"
얘네는 필요없을듯?

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +            android:fillViewport="true"
요거는 무슨 속성인가요?

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +                        android:text="WOMEN" />
텍스트들 나중에 다 추출해주실거죠? ㅎㅎ

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +                    android:overScrollMode="never"
오 이 속성 활용 좋습니다! 다른 스크롤뷰에도 한번 적용해봐요 ㅎㅎ

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +                        android:fontFamily="@font/gmarket_sans_bold"
폰트패밀리 말고 textAppearance로 속성들을 사용해주세요 !! 그래야 제가 지정해둔 친구들로 사용이 된답니당
```suggestion
                        android:textAppearance="@style/TextAppearance.Kor.Bold"
```

2023-11-24 16:55 UTC, Marchbreeze commented on app/src/main/res/layout/item_category_horizontal.xml
> +    android:layout_width="52dp"
요기도~~ 큰 값의 고정은 피해주세요

2023-11-24 16:58 UTC, Marchbreeze commented on app/src/main/res/layout/item_category_horizontal.xml
> +    android:layout_width="52dp"
다른 곳들도, 레이아웃의 크기를 고정해둔 곳들은 다 수정해주셍요 ~~ 레이아웃은 match_parent, wrap_content, 0dp로만 활용해주세요

2023-11-24 23:30 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +        android:layout_height="58dp"
엇 아니 근데 첨에는 저도 사이즈 지정 안하고wrap_content, match_parent, margin으로 사이즈를 지정해줬단 말이죠? 근데 그렇게 했더니 margin이랑 다 제대로 짰음에도 불구하고 사이즈가 지멋대로 늘거나 줄어들어서 어제 하루종일 삽질하다가 찾은 방법인디...
혹시 제대로 마진 패딩 주면 제대로 크기 비율 제대로 뜨는건가요???? 패딩 마진 제대로 줬다고 생각했는데 잘못 줘서 그렇게 나왔던건가.....?

2023-11-24 23:33 UTC, codingmy commented on app/src/main/res/layout/item_category_horizontal.xml
> +    android:layout_width="52dp"
아니 여기도!!!

2023-11-25 01:58 UTC, leeeyubin approved these changes
잘 하시는데요??! 코드 리뷰 하면서 저도 놓쳤던 부분 잡을 수 있었던 것 같아요!

2023-11-25 01:58 UTC, leeeyubin commented on app/src/main/res/layout/fragment_category.xml
> +                android:layout_width="187dp"
오호,,,,저도 아무래도 디자이너 선생님들이 정해준 사이즈대로 해야 한다고 생각해서 몇 개는 크기를 지정해줬는데  지금 생각해보니 충분히 제약으로 해결할 수 있었던 것 같기도 하네여

2023-11-25 01:58 UTC, leeeyubin commented on app/src/main/res/layout/fragment_category.xml
> +                        android:fontFamily="@font/gmarket_sans_bold"
헐 저도 쓰다가 자연스러베 다시 폰트패밀리 쓰고 있었네요,,,,

2023-11-25 01:58 UTC, leeeyubin commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
> +    private val binding: FragmentCategoryBinding get() = requireNotNull(_binding) { "바인딩 객체가 생성되지 않음" }
오호 이런 건  처음 보네용

2023-11-25 03:21 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +        android:layout_height="58dp"
레이아웃의 layout_height은 진짜 특이한 경우 아니면 wrap_content로 진행해주셔야 합니다!  아마 내부에 있는 컴포넌트들이 제약이 잘 걸려있지 않아서, wrap을 해버렸을때 안매달려있어서 딸려서 어딘가로 도망가버리는 상황...일 것 같아요 ㅎㅎ wrap_content로 변경하고, 내부 뷰들의 제약이 모두 잘 걸려있는지 확인해보세요!

2023-11-25 03:32 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +                android:layout_width="187dp"
@leeeyubin dp로 크기를 지정해주는건 패딩과 마진에만 적용하는 것이 권장됩니다! (이미지 크기를 고정시키는 상황 제외한, 일반적인 상황에서는) 나머지는 우선 기기대응이 가능한 sp로 텍스트뷰를 만들고, 그 텍스트의 크기에 맞게 제약을 걸어주며 위치를 잡아줘야 합니다.

예시.
툴바에 텍스트뷰와 이미지뷰 하나씩을 넣고, 넓은 범위의 배경을 주고싶다!
1. constraintLayout을 만든다 
- 가로 0dp, 세로 wrap, 왼쪽, 오른쪽, 위쪽 constraint parent
- 배경색을 준다 (필요 시)
2. 내부에 텍스트뷰를 넣는다
- 가로세로 wrap, 텍스트 크기 12sp, 위쪽, 아래쪽, 왼쪽 constraint parent
3. 내부에 이미지뷰를 넣는다
- 가로 wrap, 세로 0dp, 위아래 constraint to textView
- 이번 합세같은 경우 : 디자이너들이 에셋 크기를 잡아주셨기 때문에 그냥 가로세로 wrap해도 됨!

2023-11-25 03:33 UTC, Marchbreeze commented on app/src/main/res/layout/item_category_horizontal.xml
> +    android:layout_width="52dp"
@codingmy xml 고정dp 값들 다 고쳐버리기 ~~~~~

2023-11-25 03:40 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
> +    private val binding: FragmentCategoryBinding get() = requireNotNull(_binding) { "바인딩 객체가 생성되지 않음" }
@leeeyubin 유빈이도 Backing Property 써서 바인딩 만들자 ~~ 오늘 아마 세미나에서 배울듯 !!

2023-11-25 11:42 UTC, codingmy commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
> +    private val viewModel by viewModels<CategoryViewModel>()
허헣...그저 뷰모델을 정말 "쓰기"만 한...ㅎㅎ

2023-11-25 12:08 UTC, codingmy commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalViewHolder.kt
> +            binding.ivCategoryHorizontal.setImageResource(categoryHorizontalData.categoryImage)
저 궁금한거!! 지금까지는 종종 그냥 함수 선언하는 줄에서 함수가 binding 리턴하는거 아니여도 
`    fun onBind(categoryHorizontalData: CategoryHorizontal) =with(binding) {` 
이렇게 퉁쳐서 `=with(binding) `으로 썼었는데 리턴 안 할 때는 제시해준거 처럼 아예 줄 바꿔서 `with(binding) { ~}` 이걸루 구분해서 사용하는게 좋으려나요....?

2023-11-25 12:27 UTC, codingmy commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryFragment.kt
> +        return binding.root
안그래도 코리하면서 _binding null해제 해주는거 봤는데 꼭해야되는거였네용...! 반영완료!!
_adapter은 함수화하면서 적용해보겟어요~~!

2023-11-25 12:47 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +            android:layout_marginBottom="15dp"
반영했슴당~~!

2023-11-25 12:49 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +                android:id="@+id/iv_category_searchIcon"
어 이 혼종은 뭐야... 반영완료!

2023-11-25 12:53 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +        android:layout_marginEnd="0dp"
어라 맞네요!!

2023-11-25 13:26 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +                        android:fontFamily="@font/gmarket_sans_bold"
앗 헐 조장님 정성 물거품만들어버릴뻔... textAppearance로 변경하러 가요~~~!

2023-11-25 15:43 UTC, codingmy commented on app/src/main/res/layout/item_category_horizontal.xml
> +    android:layout_width="52dp"
하 성공...해냈습니다~~~~~~~!!!!

2023-11-25 15:46 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +                android:layout_width="187dp"
자세한 설명 짱....!!!! 덕분에 잘 이해해서 제가 해냇슴니다🎉🎉🎉

2023-11-25 15:50 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +        android:layout_height="58dp"
이것도!!! 덕분에 해결 완료!!!!!
아마 매달아야 될 방향에 제대로 안 매닮이 주요 원인이었던거 같아요!ㅎㅎㅎ

2023-11-25 16:14 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +            android:fillViewport="true"
저 속성이 자식 사이즈 관련 scrollView 사이즈에 대한 속성인데....분명 처음에 저 속성을 적용할 때는 뭔가 문제가 발생해서 저거를 넣었는데 지금은 삭제해도 잘 돌아가서 삭제하도록 하겠습니다!

2023-11-25 16:18 UTC, codingmy commented on app/src/main/res/layout/fragment_category.xml
> +                        android:text="WOMEN" />
허허헣...텍스트 추출을 이번에 처음해봐서 어디까지 추출해야될지 감이 안 잡혀서 그런데 그냥 xml에 들어가있는 모든 text 값들을 다 텍스트 추출해버리면 될까요...??

2023-11-26 18:09 UTC, Marchbreeze commented on app/src/main/java/org/sopt/cds29cm/presentation/category/CategoryHorizontalViewHolder.kt
> +            binding.ivCategoryHorizontal.setImageResource(categoryHorizontalData.categoryImage)
완전 취향차이! 근데 말씀해주신것처럼, =with(binding) 이 더 코틀린스러운 문법입니당 !! 리턴값을 지정해주는건 더 자바스러워서, 더 바람직한 방법으로 알고계시네요 ~~

2023-11-26 18:10 UTC, Marchbreeze commented on app/src/main/res/layout/fragment_category.xml
> +                        android:text="WOMEN" />
아래에 노란줄 그어지는 친구들은 다 추출해주시는게 좋아요 ㅎㅎ xml의 text="" 친구들이랑, 코드 내에서 토스트같은 텍스트값들은 추출하는게 더 바람직합니당

2023-11-26 18:11 UTC, Marchbreeze approved these changes
굿굿!!!! 완전 잘 수정해주셨네요 ~~~~~ LGTM

2023-11-27 00:25 UTC, merged